syncfusion-content/uwp-docs

- uwp/Pdf-Viewer/How-to/Render-PDF-pages-using-pdfium-rendering-engine.md
UWP-11147-Added corrections in Pdf-Viewer/How-to/Render-PDF-pages-using-pdfium-rendering-engine.md.
> UWP-11147-Added corrections in Pdf-Viewer/How-to/Render-PDF-pages-using-pdfium-rendering-engine.md.

- uwp/Control-Dependencies.md
added the SfTreeGrid assembly reference
> UWP-10502 Need to add the assembly requirement for Nuget in Export to PDF and Export to Excel in UWP and WPF

- uwp/DataGrid/Filtering.md
Hi @ChristoIssac,
Worked on Image Alt Text in Alexa, merge these changes.
Regards,
Gowthaman
> SEO-2008_Site_Audit_Issues

- uwp/RichTextBox/Background.md
Hi @ChristoIssac,
Worked on Site Audit Bing report issues, merge these changes.
Regards,
Gowthaman
> SEO-2154_Site_Audit_Issues

- uwp/Licensing/how-to-generate.md
- uwp/Licensing/licensing-errors.md
- uwp/Licensing/licensing-faq/how-to-upgrade-from-trial-version-after-purchasing-a-license.md
- uwp/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md
- uwp/Licensing/overview.md
- uwp/Upgrade/how-to-upgrade.md
- uwp/installation/Installation-Errors.md
- uwp/installation/offline-installer/how-to-download.md
- uwp/installation/web-installer/how-to-download.md
> IN-18200-UG-Documentation-Link-Changes-uwp-hotfix

- uwp/Image-Editor/CustomView.md
- uwp/Kanban-Board/Events.md
Worked on site audit issues, merge these changes,
Regards,
Gowthaman
> SEO-2370_Site_Audit_Issues

- uwp/Diagram/DataSource.md
Modified the Direct trac sample to github samples location link, as current Ug sample link is not exist.
> WPF-61455 modified the direct trac sample location link to github samples link

- uwp/Radial-Gauge/Labels.md
- uwp/Radial-Gauge/Pointers.md
-Corrected indent issues in UWP UG documents
> UWP-11302 : Fixed the indent issues in UWP UG

- uwp/Spell-Checker/localization.md
Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 1 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/uwp-docs/pull/244 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman
> SEO-2684-Coverage-report-pages-with-redirect

- uwp/RichTextBox/Getting-Started.md
Hi Team,
Added UG documentation for the memory leak breaking changes for the UWP platform
https://syncfusion.atlassian.net/browse/UWP-11284
Regards,
> UWP-11284  UG documentation for memory leak breaking changes

- uwp/RichTextBox/Getting-Started.md
Hi Team,
Added UG documentation for the memory leak breaking changes for the UWP platform
https://syncfusion.atlassian.net/browse/UWP-11284
Regards,
> UWP-11284 UG documentation for memory leak breaking changes

- uwp/RichTextBox/Getting-Started.md
Hi Team,
Added UG documentation for the memory leak breaking changes for the UWP platform
https://syncfusion.atlassian.net/browse/UWP-11284
Regards,
> bug(UWP-11284): Added information about the memory leak in the UWP UG

- uwp/Diagram/DataSource.md
Added equivalent code snippet of C# in data source UG page
> WPF-62258 Need to add equivalent code snippet of C# in data source UG page

- uwp/DataGrid/Export-To-PDF.md
- uwp/DataGrid/Filtering.md
- uwp/DataGrid/Summaries.md
- uwp/Masked-TextBox/Working-with-SfMaskedEdit.md
Hi Aishwarya,
Worked on page with redirect for help links, so merge these changes
Regards,
Gowthaman
> SEO-3146-coverage-page-with-redirect-help

- uwp/Scheduler/getting-started.md
Please review http to https links issue fixes.
Regards,
Sharly A.
> SEO-3153 - UWP changed http to https

- uwp/Scheduler/getting-started.md
Please review page redirect changes for UWP Sheduler.
Regards,
Sharly A.
> SEO-3222 - UWP Controls page with redirect

- uwp/Pdf-Viewer/Concepts-and-Features/UI-design-for-mobile.md
Hi @Aishwarya-Ganesan 
I have added missing H1 tags
Regards,
Beryl
> SEO-3151-UWP-Missing-H1

- uwp/Upgrade/how-to-upgrade.md
Please review permanent redirect changes for UWP.
Regards,
Sharly A.
> SEO-3353 - UWP changes

- uwp/Licensing/how-to-generate.md
Hi @Aishwarya-Ganesan ,
Have changed redirect link in UWP, please check.
Regards,
Yvone.
> SEO-3445 UWP Redirect

- uwp/RichTextBox/FAQ-Section/How-to-identify-whether-the-viewer-is-scrolled-to-the-bottom-of-the-SfRichTextBoxAdv.md
- uwp/RichTextBox/Hyperlink.md
Hi Team,
Updated UG pages regarding the features included in Volume 1, 2023 release.
Feature 3: API to access the scrollbars of the SfRichTextBoxAdv control.
Regards,
> WPF-62905: UG documentation for the Volume 1 2023 features

- uwp/Masked-TextBox/PromptChar-in-Mask.md
- uwp/Ribbon/ToolTip-Support.md
Worked on Bing report issues, so merge these changes
Regards,
Gowthaman
> SEO-3615-bing-issues

- uwp/RichTextBox/Comment.md
Hi Team,
Updated WPF UG pages with the IsCommentPanelVisible API feature.
Regards,
> ES-825519-Update UG pages for IsCommentPanelVisible API feature.

- uwp/DataGrid/Column-Types.md
Hi @Aishwarya-Ganesan ,
Have changed UWP redirect links, please review.
Regards,
Yvone.
> SEO-171762 UWP Redirect

- uwp/DataGrid/Column-Types.md
Hi @Aishwarya-Ganesan ,
Have changed Page with redirect links.
Regards,
Yvone.
> SEO-171761 UWP Redirect links

- uwp/DataGrid/Editing.md
Hi @Aishwarya-Ganesan  ,
Have changed the redirect links, Please review.
Thanks.
Regards,
Edith.
> SEO-172121-uwp-controls-redirect-links

- uwp/DataGrid/Filtering.md
Hi @gowthamanthavasiyappan ,
Have worked on changing redirect links in UWP.
Regards,
Yvone.
> SEO-172160 UWP Redirect

- uwp/DataGrid/Selection.md
- uwp/DataGrid/Serialization-and-Deserialization.md
- uwp/DataGrid/Summaries.md
- uwp/DataGrid/Unbound-Column.md
Kindly review the changes for uwp.
Regards,
Sharly A.
> SEO-172146 - UWP http to https changes

- uwp/AutoComplete/Getting-Started.md
- uwp/DatePicker/Overview.md
- uwp/Domain-UpDown/Getting-Started.md
- uwp/Numeric-TextBox/Getting-Started.md
- uwp/Radial-Slider/Getting-Started.md
Hi @MallikaRK ,
Have added the contents, please review.
Thanks.
Regards,
Edith.
> SEO-172815-UWP-controls

- uwp/Image-Editor/Getting-Started.md
- uwp/Overview.md
- uwp/TreeGrid/Getting-Started.md
Have changed UWP Page with Rediect links, please review.
Regards,
Yvone.
> SEO-174775 UWP Page with Redirect

- uwp-toc.html
- uwp/RichTextBox/FAQ-Section/How-to-paste-WordDocument-from-DocIO-in-SfRichTextBoxAdv.md
Hi Team,
Added UG content for the PasteCommand with WordDocument from DocIO as parameter in SfRichTextBoxAdv
Regards,
> ES-838522-UG documentation for PasteCommand with WordDocument as Parameter

- uwp/DataGrid/Data-Manipulation.md
- uwp/DataGrid/Interactive-Features.md
- uwp/DataGrid/Styles-and-Templates.md
- uwp/Numeric-UpDown/Getting-Started.md
- uwp/RichTextBox/Localization.md
Have changed Page with Redirect links.
Regards,
Yvone.
> SEO-175190 UWP Page with Redirect

- uwp-toc.html
Hi all,
- With this PR, we have modified the DocIO & Presentation controls direct links in UWP platform UG.
- Removed pages other than Overview and Getting Started.
Regards,
Dharanitharan A
> ES-846833-Modified DocIO & Presentation controls direct links in UWP platform UG-hotfix

- uwp/DataGrid/Paging.md
- uwp/DataGrid/Unbound-Column.md
- uwp/Numeric-UpDown/Number-Formatting.md
- uwp/TreeGrid/Getting-Started.md
Have changed UWP Page with Redirect UG.
Regards,
Yvone.
> SEO-175659 UWP Redirect links

- uwp/DataGrid/Performance-tips.md
- uwp/DataGrid/Unbound-Column.md
- uwp/TreeGrid/Data-Binding.md
Have changed Page with Redirect links.
Regards,
Yvone.
> SEO-175659 UWP Page with Redirect

- uwp-toc.html
Hi All,
Modify the TOC file for DocIo and Presentation Product.
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh
> ES-851567 Modify TOC File

- uwp/AutoComplete/Overview.md
- uwp/DataPager/Getting-Started.md
- uwp/Visual-Studio-Integration/NuGet-Packages.md
- uwp/installation/offline-installer/how-to-install.md
Have changed Page with Redirect UG.
Regards,
Yvone.
> SEO-176507 UWP Page with Redirect

- uwp/Pdf-Viewer/Concepts-and-Features/Viewing-PDF.md
Hello,
Worked on the links with redirects.
Regards,
Beryl.
> SEO-175653-UWP-Pages-With-Redirects

- uwp-toc.html
- uwp/RichTextBox/FAQ-Section/How-to-export-the-inserted-image-as-an-Embedded-image-in-HTML-in-SfRichTextBoxAdv.md
Hi Team,
Added UG content for the ImageNodeVisited API in SfRichTextBoxAdv
Regards,
> ES-855567-UG documentation for ImageNodeVisited API

- uwp/DataGrid/Clipboard-Operations.md
- uwp/Pdf-Viewer/Concepts-and-Features/Exporting-pages-as-image.md
Hello,
I have worked on links with redirects.
Regards,
Beryl.
> SEO-177279-Page-With-Redirect-UWP

- uwp-toc.html
- uwp/Pdf-Viewer/Concepts-and-Features/Printing-PDF.md
- uwp/Pdf-Viewer/Concepts-and-Features/Working-with-annotations.md
855498: Need to add UG Documentation for freetext annotation and missing modules on UWP platform.
> 855498: Need to add UG Documentation for freetext annotation and missing modules on UWP platform.

- uwp/DataGrid/Clipboard-Operations.md
Hi @MallikaRK ,
Please review the redirect link changes made
Thanks.
Regards,
Edith.
> SEO-178901-uwp-ug-page-with-redirect-links

- uwp/DataGrid/Data-Manipulation.md
- uwp/DataGrid/Sorting.md
- uwp/Pdf-Viewer/How-to/Acquire-number-of-pages-in-the-document-being-displayed.md
Hi @MallikaRK,
Worked on UWP page with redirect.
Regards,
Sharly A.
> SEO-179237-UWP-Page-With-Redirect-doc

- uwp/Charts/DataBinding.md
Added the INodifyPropertyChanged code section to the DataBinding section
> 870872-Added the INodifyPropertyChanged code section to the DataBinding section

- uwp/DataGrid/Rows.md
Hi @MallikaRK ,
Kindly review the changes.
Regards,
Edith.
> SEO-180844-UWP-issue-fix

- uwp/Diagram/Connector.md
I have changed redirection links, please review.
Regards,
Scholar.
> SEO-180837-UWP-Redirection

- uwp/DataGrid/Grouping.md
- uwp/TreeGrid/Node-CheckBox.md
Have worked on Page with Redirect, please check.
Regards,
Yvone.
> SEO-181417 UWP Redirect links

- uwp/DataGrid/Filtering.md
- uwp/installation/web-installer/how-to-download.md
Hi @gowthamanthavasiyappan,
Kindly review the referring links issue fixes changes.
Thanks.
Regards,
Edith.
> SEO-180844-uwp-refering-page

- uwp/Upgrade/how-to-upgrade.md
- uwp/installation/offline-installer/how-to-install.md
Hi @gowthamanthavasiyappan 
i have made changes on the following kindly review the below Pr
regards
Asha
> SEO-184195-UWP-INSTALATION-UPGRADE

- uwp-toc.html
Task - https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/187726/
> 187726 - Syncfusion License Validation Page Location Updated - Live

- uwp/RichTextBox/FAQ-Section/How-to-export-the-inserted-image-as-an-Embedded-image-in-HTML-in-SfRichTextBoxAdv.md
- uwp/RichTextBox/FAQ-Section/How-to-identify-whether-the-viewer-is-scrolled-to-the-bottom-of-the-SfRichTextBoxAdv.md
- uwp/RichTextBox/Getting-Started.md
Added trademark symbols for these terms in SfRichTextBoxAdv Documentation
- Syncfusion®
> ES-923791- Trademark Symbol Inclusion for Syncfusion term in UG

- uwp/Add-Syncfusion-Controls.md
- uwp/Control-Dependencies.md
- uwp/DotNET-Framework-support-History.md
- uwp/Featured-Samples.md
- uwp/Localization.md
- uwp/Overview.md
- uwp/System-Requirements.md
Hi @SubashiniMahendran
I have included the Trademark symbol in the hotfix UWP UG Document. Kindly review and merge the changes.
Regards,
Yuvaraj M
> Include trademark symbol in UWP UG document.

- uwp/Add-Syncfusion-Controls.md
- uwp/Control-Dependencies.md
- uwp/DotNET-Framework-support-History.md
- uwp/Featured-Samples.md
- uwp/Localization.md
- uwp/Overview.md
- uwp/System-Requirements.md
Hi @SubashiniMahendran
I have included the Trademark symbol in the UWP UG Document. Kindly review and merge the changes.
Regards,
Yuvaraj M
> Modified Trademark symbol from unicode to superscript registered trademark symbol

- uwp/Add-Syncfusion-Controls.md
- uwp/Control-Dependencies.md
- uwp/Deployment.md
Hi @SubashiniMahendran 
I added the trademark symbol in Deployment.md and Add-Syncfusion-Controls.md file. Kindly merge the changes.
Regards,
Yuvaraj M
> Added the trademark symbol in Deployment.md and Add-Syncfusion-Controls.md file

- uwp/Control-Dependencies.md
Removed the unwanted control list from the UG documentation for UWP platforms.
> Remove Unwanted control

- uwp/Combobox/Getting-Started.md
**Description**
Updated the Populating Items SfComboBox UG documentation.
1.Ensure proper alignment and organization of code blocks in the code snippets.
2.Clarify where to add the code for populating the items (e.g., in MainPage.xaml.cs or ProductList.cs).
3.Update the current code snippets to reflect a working implementation, ensuring the ComboBox displays the items correctly.
**Task and Ticket**
Task: https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/954922
Ticket: https://support.syncfusion.com/agent/tickets/718951
Ticket: https://support.syncfusion.com/agent/tickets/718976
> UWP-954922 : Need to update the UWP SfComboBox documentation to align code snippets and replace working examples

- uwp/RichTextBox/Getting-Started.md
Hi Team,
We have introduced some breaking changes in the UWP SfRichTextBoxAdv control. As part of this update, we’ve added relevant information along with the solution code in a table format.
Currently, this content is maintained within the Getting Started Notes section of the User Guide. However, since the table is rendered as a regular paragraph, it becomes difficult to read and locate the solution effectively.
To improve clarity and usability, please move the table content out of the Notes section and apply the modified table formatting.
Regards,
> ES-96541 – Modified Code Table for Breaking Changes Solution

- uwp/Release-notes/v31.1.17.md
> Branch Merging
